### ISSUE TITLE
ventura 13.1 

### ISSUE THREAD

**Issue by vinalinh** [roele/istats.widget#60]
i had istats working before cleaning up my disc so some things were erased + i updated to ventura and cannot figure out how to install. tried a bunch of things on other forums and posts but this is the main issue when i try to install, and i have xcode command lines installed. 
`ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0 directory.
	/Library/Ruby/Site/2.6.0/rubygems/installer.rb:712:in `verify_gem_home'
	/Library/Ruby/Site/2.6.0/rubygems/installer.rb:902:in `pre_install_checks'
	/Library/Ruby/Site/2.6.0/rubygems/installer.rb:302:in `install'
	/Library/Ruby/Site/2.6.0/rubygems/resolver/specification.rb:104:in `install'
	/Library/Ruby/Site/2.6.0/rubygems/request_set.rb:194:in `block in install'
	/Library/Ruby/Site/2.6.0/rubygems/request_set.rb:182:in `each'
	/Library/Ruby/Site/2.6.0/rubygems/request_set.rb:182:in `install'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:210:in `install_gem'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:226:in `block in install_gems'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:219:in `each'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:219:in `install_gems'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:167:in `execute'
	/Library/Ruby/Site/2.6.0/rubygems/command.rb:323:in `invoke_with_build_args'
	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:185:in `process_args'
	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:149:in `run'
	/Library/Ruby/Site/2.6.0/rubygems/gem_runner.rb:51:in `run'
	/usr/bin/gem:21:in `<main>'
`

**Comment by roele** [comment]
I assume you did use `sudo`? Already tried remove and re-install the gem?

```
❯ sudo gem uninstall iStats
Remove executables:
	istats

in addition to the gem? [Yn]  Y
Removing istats
Successfully uninstalled iStats-1.6.1

❯ sudo gem install iStats
Fetching iStats-1.6.1.gem
Building native extensions. This could take a while...
Successfully installed iStats-1.6.1
Parsing documentation for iStats-1.6.1
Installing ri documentation for iStats-1.6.1
Done installing documentation for iStats after 0 seconds
1 gem installed
```

What versions of `ruby` and `gem` are available on your system?

**Comment by vinalinh** [comment]
yes i did use sudo, ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin22] and gem 3.3.26. also just updated my xcode and i cannot remove and re-install bc it does not allow me to install
